name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Set Node options for Node 18+
        if: matrix.node-version >= '18'
        run: |
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_OUTPUT
      - run: npm ci
      - name: Build with legacy OpenSSL provider
        if: matrix.node-version >= '18'
        run: npm run build:legacy --if-present
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: Build without legacy OpenSSL provider
        if: matrix.node-version < '18'
        run: npm run build --if-present
      - run: npm test
